
#!/usr/local/bin/ansible-playbook
#
---
- name: Determine Kubernetes node to bootstrap
  connection: local
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: kubernetes_bootstrap_node
      prompt: Kubernetes bootstrap node?
      private: no

  tasks:
    - name: Adding bootstrap node to inventory
      debug:
        msg: '{{ kubernetes_bootstrap_node }}'

    - name: Adding bootstrap node to inventory
      add_host:
        hostname: '{{ kubernetes_bootstrap_node }}'
        groups:
          - kubernetes_bootstrap_node

- name: Install Kubernetes
  hosts: kubernetes_bootstrap_node
  vars:
    kubernetes_version: 1.25.8
    containerd_version: 1.7.0
    runc_version: 1.1.5
    cni_plugins_version: 1.2.0
    
    # cluster networking
    pod_network_cidr: 10.10.0.0/16
    service_network_cidr: 10.255.0.0/16

    enable_nvidia: false

    # enable add-ons
    extra_kubernetes_addons:
      - "rancher/local-path-provisioner"

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  roles:
    - role: sysprep
      tags:
        - sysprep

    - role: kubernetes
      tags:
        - kubernetes

    - role: extras
      tags:
        - extras
...
