#!/usr/local/bin/ansible-playbook
---
- name: Deploy a Kubernetes cluster
  hosts: localhost
  connection: local
  vars:
    kubernetes_version: 1.25.8
    containerd_version: 1.7.0
    runc_version: 1.1.5
    cni_plugins_version: 1.2.0
    
    # cluster networking
    pod_network_cidr: 10.10.0.0/16
    service_network_cidr: 10.255.0.0/16

    enable_nvidia: false

    # enable add-ons
    extra_kubernetes_addons:
      - "rancher/local-path-provisioner"

  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  roles:
    - role: sysprep
      tags:
        - sysprep

    - role: kubernetes
      tags:
        - kubernetes

    - role: nvidia
      when: enable_nvidia == true
      tags:
        - nvidia

    - role: extras
      tags:
        - extras
