---
- name: Install Nvidia driver pre-reqs
  apt:
    name: '{{ item }}'
    state: present
  loop:
    - 'linux-headers-{{ ansible_kernel }}'
    - build-essential

- name: Download Nvidia driver
  command: curl -L -o /tmp/nvidia_driver.run "https://download.nvidia.com/XFree86/Linux-x86_64/530.41.03/NVIDIA-Linux-x86_64-530.41.03.run"
  args:
    creates: /tmp/nvidia_driver.run

- name: Make /tmp/nvidia_driver.run executable
  file:
    path: /tmp/nvidia_driver.run
    mode: 0755

- name: Install Nvidia driver
  command: /tmp/nvidia_driver.run -m=kernel-open  --disable-nouveau --silent
  args:
    creates: /usr/bin/nvidia-smi

- name: Create nvidia.conf
  copy:
    dest: /etc/modprobe.d/nvidia.conf
    content: |-
      options nvidia NVreg_OpenRmEnableUnsupportedGpus=1
  notify: update-initramfs

- name: Add the nvidia-docker repo key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add nvidia-docker repo
  shell: curl -s -L https://nvidia.github.io/nvidia-docker/debian11/nvidia-docker.list > /etc/apt/sources.list.d/nvidia-docker.list
  args:
    creates: /etc/apt/sources.list.d/nvidia-docker.list
  notify: update-apt-cache

- meta: flush_handlers

- name: Install nvidia-container-runtime
  apt:
    name: nvidia-container-runtime

- name: Reboot the machine (Wait for 5 min)
  reboot:
    reboot_timeout: 300
