---
- name: Install packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: True
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Install Kubernetes repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    state: present

- name: Install Kuberentes repo
  apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main'
    state: present
    filename: kubernetes

