- debug:
    msg: "Setting up rancher/local-host-provisioner"

- name: Ensure that /opt folder exists
  file:
    path: /opt
    state: directory

- name: Get the deployment manifest
  command: curl -o /opt/local-host-provisioner.yaml -L "https://raw.githubusercontent.com/rancher/local-path-provisioner/{{ local_host_provisioner_version }}/deploy/local-path-storage.yaml"
  args:
    creates: /opt/local-host-provisioner.yaml

- name: Apply the manifest
  shell: kubectl apply -f /opt/local-host-provisioner.yaml && touch /opt/local-host-provisioner.deployed
  args:
    creates: /opt/local-host-provisioner.deployed

- name: Make local-path the default provisioner
  shell: "kubectl patch storageclass local-path -p '{\"metadata\": {\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}' && touch /opt/local-host-provisioner.is_default"
  args:
    creates: /opt/local-host-provisioner.is_default
